#include "mx_funcs.h"

#define true 1
#define false 0
struct textureresource { string filename; string colorspace; };
#define BSDF closure color
#define EDF closure color
#define VDF closure color
struct surfaceshader { closure color bsdf; closure color edf; float opacity; };
#define volumeshader closure color
#define displacementshader vector
#define lightshader closure color
#define MATERIAL closure color

#define M_FLOAT_EPS 1e-8

void mx_roughness_anisotropy(float roughness, float anisotropy, output vector2 result)
{
    float roughness_sqr = clamp(roughness*roughness, M_FLOAT_EPS, 1.0);
    if (anisotropy > 0.0)
    {
        float aspect = sqrt(1.0 - clamp(anisotropy, 0.0, 0.98));
        result.x = min(roughness_sqr / aspect, 1.0);
        result.y = roughness_sqr * aspect;
    }
    else
    {
        result.x = roughness_sqr;
        result.y = roughness_sqr;
    }
}

void mx_luminance_color3(color in, color lumacoeffs, output color result)
{
    result = dot(in, lumacoeffs);
}

matrix rotationMatrix(vector axis, float angle)
{
    vector nAxis = normalize(axis);
    float s = sin(angle);
    float c = cos(angle);
    float oc = 1.0 - c;

    return matrix(oc * nAxis[0] * nAxis[0] + c,             oc * nAxis[0] * nAxis[1] - nAxis[2] * s,  oc * nAxis[2] * nAxis[0] + nAxis[1] * s,  0.0,
                  oc * nAxis[0] * nAxis[1] + nAxis[2] * s,  oc * nAxis[1] * nAxis[1] + c,             oc * nAxis[1] * nAxis[2] - nAxis[0] * s,  0.0,
                  oc * nAxis[2] * nAxis[0] - nAxis[1] * s,  oc * nAxis[1] * nAxis[2] + nAxis[0] * s,  oc * nAxis[2] * nAxis[2] + c,             0.0,
                  0.0,                                      0.0,                                      0.0,                                      1.0);
}

void mx_rotate_vector3(vector _in, float amount, vector axis, output vector result)
{
    float rotationRadians = radians(amount);
    matrix m = rotationMatrix(axis, rotationRadians);
    vector4 trans = transform(m, vector4(_in[0], _in[1], _in[2], 1.0));
    result = vector(trans.x, trans.y, trans.z);
}

void mx_artistic_ior(color reflectivity, color edge_color, output vector ior, output vector extinction)
{
    // "Artist Friendly Metallic Fresnel", Ole Gulbrandsen, 2014
    // http://jcgt.org/published/0003/04/03/paper.pdf

    color r = clamp(reflectivity, 0.0, 0.99);
    color r_sqrt = sqrt(r);
    color n_min = (1.0 - r) / (1.0 + r);
    color n_max = (1.0 + r_sqrt) / (1.0 - r_sqrt);
    ior = mix(n_max, n_min, edge_color);

    color np1 = ior + 1.0;
    color nm1 = ior - 1.0;
    color k2 = (np1*np1 * r - nm1*nm1) / (1.0 - r);
    k2 = max(k2, 0.0);
    extinction = sqrt(k2);
}

void mx_dielectric_bsdf(float weight, color tint, float ior, vector2 roughness, float thinfilm_thickness, float thinfilm_ior, normal N, vector U, string distribution, string scatter_mode, output BSDF bsdf)
{
    if (scatter_mode == "R")
    {
        bsdf = weight * dielectric_bsdf(N, U, tint, color(0.0), roughness.x, roughness.y, ior, distribution, "thinfilm_thickness", thinfilm_thickness, "thinfilm_ior", thinfilm_ior);
    }
    else if (scatter_mode == "T")
    {
        bsdf = weight * dielectric_bsdf(N, U, color(0.0), tint, roughness.x, roughness.y, ior, distribution, "thinfilm_thickness", thinfilm_thickness, "thinfilm_ior", thinfilm_ior);
    }
    else
    {
        bsdf = weight * dielectric_bsdf(N, U, tint, tint, roughness.x, roughness.y, ior, distribution, "thinfilm_thickness", thinfilm_thickness, "thinfilm_ior", thinfilm_ior);
    }
}

void mx_subsurface_bsdf(float weight, color _color, color radius, float anisotropy, normal N, output BSDF bsdf)
{
    // TODO: Subsurface closure is not supported by vanilla OSL.
    bsdf = _color * weight * diffuse(N);
}

void NG_convert_float_color3(float in, output color out)
{
    color combine_out = color( in,in,in );
    out = combine_out;
}

float mx_square(float x)
{
    return x*x;
}

vector2 mx_square(vector2 x)
{
    return x*x;
}

vector mx_square(vector x)
{
    return x*x;
}

vector4 mx_square(vector4 x)
{
    return x*x;
}

float mx_pow5(float x)
{
    return mx_square(mx_square(x)) * x;
}

color mx_fresnel_conductor(float cosTheta, vector n, vector k)
{
   float c2 = cosTheta*cosTheta;
   vector n2_k2 = n*n + k*k;
   vector nc2 = 2.0 * n * cosTheta;

   vector rs_a = n2_k2 + c2;
   vector rp_a = n2_k2 * c2 + 1.0;
   vector rs = (rs_a - nc2) / (rs_a + nc2);
   vector rp = (rp_a - nc2) / (rp_a + nc2);

   return 0.5 * (rs + rp);
}

// Standard Schlick Fresnel
float mx_fresnel_schlick(float cosTheta, float F0)
{
    float x = clamp(1.0 - cosTheta, 0.0, 1.0);
    float x5 = mx_pow5(x);
    return F0 + (1.0 - F0) * x5;
}
color mx_fresnel_schlick(float cosTheta, color F0)
{
    float x = clamp(1.0 - cosTheta, 0.0, 1.0);
    float x5 = mx_pow5(x);
    return F0 + (1.0 - F0) * x5;
}

// Generalized Schlick Fresnel
float mx_fresnel_schlick(float cosTheta, float F0, float F90)
{
    float x = clamp(1.0 - cosTheta, 0.0, 1.0);
    float x5 = mx_pow5(x);
    return mix(F0, F90, x5);
}
color mx_fresnel_schlick(float cosTheta, color F0, color F90)
{
    float x = clamp(1.0 - cosTheta, 0.0, 1.0);
    float x5 = mx_pow5(x);
    return mix(F0, F90, x5);
}

// Generalized Schlick Fresnel with a variable exponent
color mx_fresnel_schlick(float cosTheta, float f0, float f90, float exponent)
{
    float x = clamp(1.0 - cosTheta, 0.0, 1.0);
    return mix(f0, f90, pow(x, exponent));
}
color mx_fresnel_schlick(float cosTheta, color f0, color f90, float exponent)
{
    float x = clamp(1.0 - cosTheta, 0.0, 1.0);
    return mix(f0, f90, pow(x, exponent));
}

void mx_generalized_schlick_edf(color color0, color color90, float exponent, EDF base, output EDF result)
{
    float NdotV = fabs(dot(N,-I));
    color f = mx_fresnel_schlick(NdotV, color0, color90, exponent);
    result = base * f;
}

void mx_surface(BSDF bsdf, EDF edf, float opacity, int thin_walled, output surfaceshader result)
{
    result.bsdf    = bsdf;
    result.edf     = edf;
    result.opacity = clamp(opacity, 0.0, 1.0);
}

surface NG_standard_surface_surfaceshader_100_out
[[
    string mtlx_category = "output",
    string mtlx_name = "out"
]]
(
    float base = 0.800000
    [[
        string widget = "number"
    ]],
    color base_color = color(1.000000, 1.000000, 1.000000),
    float diffuse_roughness = 0.000000
    [[
        string widget = "number"
    ]],
    float metalness = 0.000000
    [[
        string widget = "number"
    ]],
    float specular = 1.000000
    [[
        string widget = "number"
    ]],
    color specular_color = color(1.000000, 1.000000, 1.000000),
    float specular_roughness = 0.200000
    [[
        string widget = "number"
    ]],
    float specular_IOR = 1.500000
    [[
        string widget = "number"
    ]],
    float specular_anisotropy = 0.000000
    [[
        string widget = "number"
    ]],
    float specular_rotation = 0.000000
    [[
        string widget = "number"
    ]],
    float transmission = 0.000000
    [[
        string widget = "number"
    ]],
    color transmission_color = color(1.000000, 1.000000, 1.000000),
    float transmission_extra_roughness = 0.000000
    [[
        string widget = "number"
    ]],
    float subsurface1 = 0.000000
    [[
        string widget = "number"
    ]],
    color subsurface_color = color(1.000000, 1.000000, 1.000000),
    color subsurface_radius = color(1.000000, 1.000000, 1.000000),
    float subsurface_scale = 1.000000
    [[
        string widget = "number"
    ]],
    float subsurface_anisotropy = 0.000000
    [[
        string widget = "number"
    ]],
    float sheen1 = 0.000000
    [[
        string widget = "number"
    ]],
    color sheen_color = color(1.000000, 1.000000, 1.000000),
    float sheen_roughness = 0.300000
    [[
        string widget = "number"
    ]],
    float coat = 0.000000
    [[
        string widget = "number"
    ]],
    color coat_color = color(1.000000, 1.000000, 1.000000),
    float coat_roughness = 0.100000
    [[
        string widget = "number"
    ]],
    float coat_anisotropy = 0.000000
    [[
        string widget = "number"
    ]],
    float coat_rotation = 0.000000
    [[
        string widget = "number"
    ]],
    float coat_IOR = 1.500000
    [[
        string widget = "number"
    ]],
    vector coat_normal = N,
    float coat_affect_color = 0.000000
    [[
        string widget = "number"
    ]],
    float coat_affect_roughness = 0.000000
    [[
        string widget = "number"
    ]],
    float thin_film_thickness = 0.000000
    [[
        string widget = "number"
    ]],
    float thin_film_IOR = 1.500000
    [[
        string widget = "number"
    ]],
    float emission1 = 0.000000
    [[
        string widget = "number"
    ]],
    color emission_color = color(1.000000, 1.000000, 1.000000),
    color opacity = color(1.000000, 1.000000, 1.000000),
    int thin_walled = 0
    [[
        string widget = "checkBox"
    ]],
    vector normal1 = N,
    vector tangent = dPdu,
    float coat_tangent_rotate_degree_in2 = 360.000000
    [[
        string widget = "number"
    ]],
    float tangent_rotate_degree_in2 = 360.000000
    [[
        string widget = "number"
    ]],
    string sheen_bsdf_mode = "conty_kulla",
    float subsurface_color_nonnegative_in2 = 0.000000
    [[
        string widget = "number"
    ]],
    float coat_clamped_low = 0.000000
    [[
        string widget = "number"
    ]],
    float coat_clamped_high = 1.000000
    [[
        string widget = "number"
    ]],
    float base_color_nonnegative_in2 = 0.000000
    [[
        string widget = "number"
    ]],
    color coat_attenuation_bg = color(1.000000, 1.000000, 1.000000),
    float one_minus_coat_ior_in1 = 1.000000
    [[
        string widget = "number"
    ]],
    float one_plus_coat_ior_in1 = 1.000000
    [[
        string widget = "number"
    ]],
    color opacity_luminance_lumacoeffs = color(0.272229, 0.674082, 0.053689),
    float transmission_roughness_clamped_low = 0.000000
    [[
        string widget = "number"
    ]],
    float transmission_roughness_clamped_high = 1.000000
    [[
        string widget = "number"
    ]],
    int opacity_luminance_float_index = 0
    [[
        string widget = "number"
    ]],
    float coat_affected_roughness_fg = 1.000000
    [[
        string widget = "number"
    ]],
    float coat_affected_transmission_roughness_fg = 1.000000
    [[
        string widget = "number"
    ]],
    float coat_gamma_in2 = 1.000000
    [[
        string widget = "number"
    ]],
    float coat_tangent_value2 = 0.000000
    [[
        string widget = "number"
    ]],
    float main_tangent_value2 = 0.000000
    [[
        string widget = "number"
    ]],
    float one_minus_coat_ior_to_F0_in1 = 1.000000
    [[
        string widget = "number"
    ]],
    color coat_bsdf_tint = color(1.000000, 1.000000, 1.000000),
    float coat_bsdf_thinfilm_thickness = 0.000000
    [[
        string widget = "number"
    ]],
    float coat_bsdf_thinfilm_ior = 1.500000
    [[
        string widget = "number"
    ]],
    string coat_bsdf_distribution = "ggx",
    string coat_bsdf_scatter_mode = "R",
    float metal_bsdf_weight = 1.000000
    [[
        string widget = "number"
    ]],
    string metal_bsdf_distribution = "ggx",
    string specular_bsdf_distribution = "ggx",
    string specular_bsdf_scatter_mode = "R",
    float transmission_bsdf_weight = 1.000000
    [[
        string widget = "number"
    ]],
    float transmission_bsdf_thinfilm_thickness = 0.000000
    [[
        string widget = "number"
    ]],
    float transmission_bsdf_thinfilm_ior = 1.500000
    [[
        string widget = "number"
    ]],
    string transmission_bsdf_distribution = "ggx",
    string transmission_bsdf_scatter_mode = "T",
    float translucent_bsdf_weight = 1.000000
    [[
        string widget = "number"
    ]],
    float subsurface_bsdf_weight = 1.000000
    [[
        string widget = "number"
    ]],
    int diffuse_bsdf_energy_compensation = 0
    [[
        string widget = "checkBox"
    ]],
    color coat_emission_edf_color90 = color(0.000000, 0.000000, 0.000000),
    float coat_emission_edf_exponent = 5.000000
    [[
        string widget = "number"
    ]],
    int shader_constructor_thin_walled = 0
    [[
        string widget = "checkBox"
    ]],
    output closure color out = 0
)
{
    closure color null_closure = 0;
    vector2 coat_roughness_vector_out = vector2(0.0, 0.0);
    mx_roughness_anisotropy(coat_roughness, coat_anisotropy, coat_roughness_vector_out);
    float coat_tangent_rotate_degree_out = coat_rotation * coat_tangent_rotate_degree_in2;
    color metal_reflectivity_out = base_color * base;
    color metal_edgecolor_out = specular_color * specular;
    float coat_affect_roughness_multiply1_out = coat_affect_roughness * coat;
    float tangent_rotate_degree_out = specular_rotation * tangent_rotate_degree_in2;
    float transmission_roughness_add_out = specular_roughness + transmission_extra_roughness;
    color subsurface_color_nonnegative_out = max(subsurface_color, subsurface_color_nonnegative_in2);
    float coat_clamped_out = clamp(coat, coat_clamped_low, coat_clamped_high);
    color subsurface_radius_scaled_out = subsurface_radius * subsurface_scale;
    float subsurface_selector_out = float(thin_walled);
    color base_color_nonnegative_out = max(base_color, base_color_nonnegative_in2);
    color coat_attenuation_out = mix(coat_attenuation_bg, coat_color, coat);
    float one_minus_coat_ior_out = one_minus_coat_ior_in1 - coat_IOR;
    float one_plus_coat_ior_out = one_plus_coat_ior_in1 + coat_IOR;
    color emission_weight_out = emission_color * emission1;
    color opacity_luminance_out = color(0.0);
    mx_luminance_color3(opacity, opacity_luminance_lumacoeffs, opacity_luminance_out);
    vector coat_tangent_rotate_out = vector(0.0);
    mx_rotate_vector3(tangent, coat_tangent_rotate_degree_out, coat_normal, coat_tangent_rotate_out);
    color artistic_ior_ior = color(0.0);
    color artistic_ior_extinction = color(0.0);
    mx_artistic_ior(metal_reflectivity_out, metal_edgecolor_out, artistic_ior_ior, artistic_ior_extinction);
    float coat_affect_roughness_multiply2_out = coat_affect_roughness_multiply1_out * coat_roughness;
    vector tangent_rotate_out = vector(0.0);
    mx_rotate_vector3(tangent, tangent_rotate_degree_out, normal1, tangent_rotate_out);
    float transmission_roughness_clamped_out = clamp(transmission_roughness_add_out, transmission_roughness_clamped_low, transmission_roughness_clamped_high);
    float coat_gamma_multiply_out = coat_clamped_out * coat_affect_color;
    float coat_ior_to_F0_sqrt_out = one_minus_coat_ior_out / one_plus_coat_ior_out;
    float opacity_luminance_float_out = mx_extract(opacity_luminance_out, opacity_luminance_float_index);
    vector coat_tangent_rotate_normalize_out = normalize(coat_tangent_rotate_out);
    float coat_affected_roughness_out = mix(specular_roughness, coat_affected_roughness_fg, coat_affect_roughness_multiply2_out);
    vector tangent_rotate_normalize_out = normalize(tangent_rotate_out);
    float coat_affected_transmission_roughness_out = mix(transmission_roughness_clamped_out, coat_affected_transmission_roughness_fg, coat_affect_roughness_multiply2_out);
    float coat_gamma_out = coat_gamma_multiply_out + coat_gamma_in2;
    float coat_ior_to_F0_out = coat_ior_to_F0_sqrt_out * coat_ior_to_F0_sqrt_out;
    vector coat_tangent_out = mx_ternary(coat_anisotropy > coat_tangent_value2, coat_tangent_rotate_normalize_out, tangent);
    vector2 main_roughness_out = vector2(0.0, 0.0);
    mx_roughness_anisotropy(coat_affected_roughness_out, specular_anisotropy, main_roughness_out);
    vector main_tangent_out = mx_ternary(specular_anisotropy > main_tangent_value2, tangent_rotate_normalize_out, tangent);
    vector2 transmission_roughness_out = vector2(0.0, 0.0);
    mx_roughness_anisotropy(coat_affected_transmission_roughness_out, specular_anisotropy, transmission_roughness_out);
    color coat_affected_subsurface_color_out = pow(subsurface_color_nonnegative_out, coat_gamma_out);
    color coat_affected_diffuse_color_out = pow(base_color_nonnegative_out, coat_gamma_out);
    float one_minus_coat_ior_to_F0_out = one_minus_coat_ior_to_F0_in1 - coat_ior_to_F0_out;
    color emission_color0_out = color(0.0);
    NG_convert_float_color3(one_minus_coat_ior_to_F0_out, emission_color0_out);
    BSDF coat_bsdf_out = null_closure;
    mx_dielectric_bsdf(coat, coat_bsdf_tint, coat_IOR, coat_roughness_vector_out, coat_bsdf_thinfilm_thickness, coat_bsdf_thinfilm_ior, coat_normal, coat_tangent_out, coat_bsdf_distribution, coat_bsdf_scatter_mode, coat_bsdf_out);
    BSDF metal_bsdf_out = metal_bsdf_weight * conductor_bsdf(normal1, main_tangent_out, main_roughness_out.x, main_roughness_out.y, artistic_ior_ior, artistic_ior_extinction, metal_bsdf_distribution, "thinfilm_thickness", thin_film_thickness, "thinfilm_ior", thin_film_IOR);
    BSDF specular_bsdf_out = null_closure;
    mx_dielectric_bsdf(specular, specular_color, specular_IOR, main_roughness_out, thin_film_thickness, thin_film_IOR, normal1, main_tangent_out, specular_bsdf_distribution, specular_bsdf_scatter_mode, specular_bsdf_out);
    BSDF transmission_bsdf_out = null_closure;
    mx_dielectric_bsdf(transmission_bsdf_weight, transmission_color, specular_IOR, transmission_roughness_out, transmission_bsdf_thinfilm_thickness, transmission_bsdf_thinfilm_ior, normal1, main_tangent_out, transmission_bsdf_distribution, transmission_bsdf_scatter_mode, transmission_bsdf_out);
    BSDF sheen_bsdf_out = sheen1 * sheen_bsdf(normal1, sheen_color, sheen_roughness);
    BSDF translucent_bsdf_out = translucent_bsdf_weight * translucent_bsdf(normal1, coat_affected_subsurface_color_out);
    BSDF subsurface_bsdf_out = null_closure;
    mx_subsurface_bsdf(subsurface_bsdf_weight, coat_affected_subsurface_color_out, subsurface_radius_scaled_out, subsurface_anisotropy, normal1, subsurface_bsdf_out);
    BSDF selected_subsurface_bsdf_out = mix(subsurface_bsdf_out, translucent_bsdf_out, subsurface_selector_out);
    BSDF diffuse_bsdf_out = base * oren_nayar_diffuse_bsdf(normal1, coat_affected_diffuse_color_out, diffuse_roughness);
    BSDF subsurface_mix_out = mix(diffuse_bsdf_out, selected_subsurface_bsdf_out, subsurface1);
    BSDF sheen_layer_out = layer(sheen_bsdf_out, subsurface_mix_out);
    BSDF transmission_mix_out = mix(sheen_layer_out, transmission_bsdf_out, transmission);
    BSDF specular_layer_out = layer(specular_bsdf_out, transmission_mix_out);
    BSDF metalness_mix_out = mix(specular_layer_out, metal_bsdf_out, metalness);
    BSDF thin_film_layer_attenuated_out = (coat_attenuation_out * metalness_mix_out);
    BSDF coat_layer_out = layer(coat_bsdf_out, thin_film_layer_attenuated_out);
    EDF emission_edf_out = uniform_edf(emission_weight_out);
    EDF coat_tinted_emission_edf_out = (coat_color * emission_edf_out);
    EDF coat_emission_edf_out = null_closure;
    mx_generalized_schlick_edf(emission_color0_out, coat_emission_edf_color90, coat_emission_edf_exponent, coat_tinted_emission_edf_out, coat_emission_edf_out);
    EDF blended_coat_emission_edf_out = mix(emission_edf_out, coat_emission_edf_out, coat);
    surfaceshader shader_constructor_out = surfaceshader(null_closure, null_closure, 1.0);
    mx_surface(coat_layer_out, blended_coat_emission_edf_out, opacity_luminance_float_out, shader_constructor_thin_walled, shader_constructor_out);
    {
        float opacity_weight = clamp(shader_constructor_out.opacity, 0.0, 1.0);
        out = (shader_constructor_out.bsdf + shader_constructor_out.edf) * opacity_weight + transparent() * (1.0 - opacity_weight);
    }
}

